import React, { useState } from 'react';
const topics = [
    { title: 'Problems on Trains', path: '/problems-on-trains', solved: 10, total: 20 },
    { title: 'Problems on Time and Distance', path: '/problems-on-time-and-distance', solved: 15, total: 30 },
    { title: 'Problems on Height and Distance', path: '/problems-on-height-and-distance', solved: 5, total: 10 },
    { title: 'Problems on Time and Work', path: '/problems-on-time-and-work', solved: 7, total: 20 },
    { title: 'Problems on Simple Interest', path: '/problems-on-simple-interest', solved: 8, total: 25 },
    { title: 'Problems on Compound Interest', path: '/problems-on-compound-interest', solved: 9, total: 18 },
    { title: 'Problems on Profit and loss', path: '/problems-on-profit-and-loss', solved: 12, total: 24 },
    { title: 'Problems on Partnership', path: '/problems-on-partnership', solved: 14, total: 22 },
    { title: 'Problems on Percentage', path: '/problems-on-percentage', solved: 13, total: 28 },
    { title: 'Problems on Calendar', path: '/problems-on-calendar', solved: 11, total: 21 },
    { title: 'Problems on Clock', path: '/problems-on-clock', solved: 16, total: 23 },
    { title: 'Problems on Average', path: '/problems-on-average', solved: 6, total: 12 },
    { title: 'Problems on Volume and Surface Area', path: '/problems-on-volume-and-surface-area', solved: 18, total: 30 },
    { title: 'Problems on Permutation and Combination', path: '/problems-on-permutation-and-combination', solved: 19, total: 40 },
    { title: 'Problems on Numbers', path: '/problems-on-numbers', solved: 10, total: 20 },
    { title: 'Problems on H.C.F and L.C.M', path: '/problems-on-hcf-and-lcm', solved: 15, total: 35 },
    // { title: 'Problems on Decimal Fraction', path: '/problems-on-decimal-fraction', solved: 8, total: 15 },
    { title: 'Problems on Simplification', path: '/problems-on-simplification', solved: 7, total: 14 },
    // { title: 'Problems on Square Root and Cube Root', path: '/problems-on-square-root-and-cube-root', solved: 12, total: 20 },
    // { title: 'Problems on Surds and Indices', path: '/problems-on-surds-and-indices', solved: 9, total: 18 },
    { title: 'Problems on Ratio and Proportion', path: '/problems-on-ratio-and-proportion', solved: 13, total: 22 },
    { title: 'Problems on Chain Rule', path: '/problems-on-chain-rule', solved: 11, total: 19 },
    { title: 'Problems on Pipes and Cistern', path: '/problems-on-pipes-and-cistern', solved: 10, total: 20 },
    { title: 'Problems on Boats and Streams', path: '/problems-on-boats-and-streams', solved: 15, total: 25 },
    { title: 'Problems on Alligation or Mixture', path: '/problems-on-alligation-or-mixture', solved: 17, total: 30 },
    { title: 'Problems on Logarithm', path: '/problems-on-logarithm', solved: 5, total: 15 },
    { title: 'Problems on Races and Games', path: '/problems-on-races-and-games', solved: 6, total: 18 },
    { title: 'Problems on Stocks and Shares', path: '/problems-on-stocks-and-shares', solved: 9, total: 20 },
    { title: 'Problems on Probability', path: '/problems-on-probability', solved: 8, total: 12 },
    { title: 'Problems on True Discount', path: '/problems-on-true-discount', solved: 14, total: 22 },
    { title: 'Problems on Bankers Discount', path: '/problems-on-bankers-discount', solved: 11, total: 18 },
    { title: 'Problems on Odd Man Out and Series', path: '/problems-on-odd-man-out-and-series', solved: 10, total: 15 },
];

export default topics;